In [64]:
import pandas as pd
df1=pd.read_csv("train.csv")
df2=pd.read_csv("stores.csv")
df3=pd.read_csv("features.csv")

#

#  Walmart Sales Forecasting using Machine Learning

##  Objective
- Analyze historical sales data
- Build predictive models
- Optimize performance
- Support business decisions

In [65]:
df = df1.merge(df3, on=['Store','Date'], how='left')
df = df.merge(df2, on='Store', how='left')
df.isnull().sum()

Store                0
Dept                 0
Date                 0
Weekly_Sales         0
IsHoliday_x          0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
IsHoliday_y          0
Type                 0
Size                 0
dtype: int64

In [66]:
# Markdown  represent discount / promotion values applied to products.
md_cols = ['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']
df[md_cols] = df[md_cols].fillna(0)

In [67]:
df

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,False,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,True,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,False,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,False,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,False,B,118221
421566,45,98,2012-10-05,628.10,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,False,B,118221
421567,45,98,2012-10-12,1061.02,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,False,B,118221
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,False,B,118221
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,False,B,118221

##  Exploratory Data Analysis
- Trend analysis
- Correlation check
- Holiday impact
- ##  Data Preprocessing
- Convert date
- Feature engineering
- Handle missing values

In [68]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday_x     0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday_y     0
Type            0
Size            0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Week'] = df['Date'].dt.isocalendar().week
df.drop('Date', axis=1, inplace=True)

In [71]:
(df['IsHoliday_x']!=df['IsHoliday_y']).sum()

np.int64(0)

In [72]:
df.columns

Index(['Store', 'Dept', 'Weekly_Sales', 'IsHoliday_x', 'Temperature',
       'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4',
       'MarkDown5', 'CPI', 'Unemployment', 'IsHoliday_y', 'Type', 'Size',
       'Year', 'Month', 'Week'],
      dtype='object')

In [73]:
y=df['Weekly_Sales']
x=df.drop('Weekly_Sales',axis=1)

In [74]:
# Is IsHoliday used for label encoding?
# NO — it is NOT used for label encoding (in most cases).
#t is already a binary feature (0/1 or True/False).

In [75]:
#check whether your dataset is balanced or imbalanced, you first need to understand:
# This is a regression dataset (target = Weekly_Sales)
#So “balanced/imbalanced” like classification does NOT directly apply

In [76]:
x=x.drop('IsHoliday_y', axis=1)

In [77]:
pd.get_dummies(x,columns=['Type'],dtype=int)

,Store,Dept,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Size,Year,Month,Week,Type_A,Type_B,Type_C
0,1,1,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,151315,2010,2,5,1,0,0
1,1,1,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,151315,2010,2,6,1,0,0
2,1,1,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,151315,2010,2,7,1,0,0
3,1,1,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,151315,2010,2,8,1,0,0
4,1,1,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,151315,2010,3,9,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,118221,2012,9,39,0,1,0
421566,45,98,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,118221,2012,10,40,0,1,0
421567,45,98,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,118221,2012,10,41,0,1,0
421568,45,98,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,118221,2012,10,42,0,1,0
421569,45,98,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,118221,2012,10,43,0,1,0

In [78]:
x

,Store,Dept,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Year,Month,Week
0,1,1,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,A,151315,2010,2,5
1,1,1,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,A,151315,2010,2,6
2,1,1,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,A,151315,2010,2,7
3,1,1,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,A,151315,2010,2,8
4,1,1,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,A,151315,2010,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,B,118221,2012,9,39
421566,45,98,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,B,118221,2012,10,40
421567,45,98,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,B,118221,2012,10,41
421568,45,98,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,B,118221,2012,10,42
421569,45,98,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,B,118221,2012,10,43

In [79]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
x['Type']=le.fit_transform(x['Type'])
x

,Store,Dept,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Year,Month,Week
0,1,1,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,0,151315,2010,2,5
1,1,1,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,0,151315,2010,2,6
2,1,1,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,0,151315,2010,2,7
3,1,1,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,0,151315,2010,2,8
4,1,1,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,0,151315,2010,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,1,118221,2012,9,39
421566,45,98,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,1,118221,2012,10,40
421567,45,98,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,1,118221,2012,10,41
421568,45,98,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,1,118221,2012,10,42
421569,45,98,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,1,118221,2012,10,43

In [80]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x=st.fit_transform(x)

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [82]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [83]:
y_pred=model.predict(x_test)

In [84]:
from sklearn.metrics import r2_score, mean_squared_error

In [85]:
mse= mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

import numpy as np
rmse=round((np.sqrt(mse)),2)
print("mean_squared_error",mse)
print("rmse",rmse, )
print("accuracy is", round(r2*100,2),"%")

mean_squared_error 464045339.6143491
rmse 21541.71
accuracy is 8.65 %

In [86]:
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

mse= mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

import numpy as np
rmse=round((np.sqrt(mse)),2)
print("mean_squared_error",mse)
print("rmse",rmse, )
print("accuracy is", round(r2*100,2),"%")

mean_squared_error 368300622.79607224
rmse 19191.16
accuracy is 27.5 %

In [87]:
print(y_test,y_pred)

167003    64839.21
260379     2114.65
415817     6520.50
205993     7641.66
256641     7339.29
            ...
404201    79994.53
25200       941.50
22484      3701.57
159444    12272.82
30651     57167.63
Name: Weekly_Sales, Length: 84314, dtype: float64 [34969.326  7517.808  4591.152 ...  4498.31  17361.142 26291.614]

In [88]:

from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=5)
model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=5)

In [89]:
y_pred=model.predict(x_test)

In [90]:
mse= mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

import numpy as np
rmse=round((np.sqrt(mse)),2)
print("mean_squared_error",mse)
print("rmse",rmse, )
print("accuracy is", round(r2*100,2),"%")

mean_squared_error 16541692.266491579
rmse 4067.15
accuracy is 96.74 %

In [91]:

from sklearn.tree import DecisionTreeRegressor
model= DecisionTreeRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [92]:
mse= mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

import numpy as np
rmse=round((np.sqrt(mse)),2)
print("mean_squared_error",mse)
print("rmse",rmse, )
print("accuracy is", round(r2*100,2),"%")

mean_squared_error 22150570.643837273
rmse 4706.44
accuracy is 95.64 %

## Optimization Techniques
- Hyperparameter tuning (GridSearchCV)
- Feature selection
- Cross-validation
- Ensemble learning

In [110]:
from sklearn.model_selection import GridSearchCV

param={
#n_estimators=[13,20,55],
    'max_depth': [3, 5, 8, 12],
    'min_samples_split': [2, 5, 10],
   # 'min_samples_leaf': [1, 2, 5]

#learning_rate=[0.1,0.3]
}

In [108]:

model = GridSearchCV(RandomForestRegressor(),param,cv=2)

In [ ]:
model.fit(x_train,y_train)

##  Final Result
Best Model: Random Forest with GridSearchCV

##  Business Impact
- Better inventory planning
- Reduced losses
- Improved forecasting